### PR TITLE
Added useful-aliases file

### PR DESCRIPTION
**Pull request by JacobCallahan**
Some miscellaneous bash aliases and functions.

### CODE REVIEW

**Comment by sthirugn** [comment]
you may want to rename the file and add some comments here mentioning that this is related to or used in conjunction with chd-setup.yaml

**Comment by JacobCallahan** [comment]
I'm up for renaming the file, but I'm not sure what the most appropriate name would be. Initial thought was bash-things.txt. I could add some general comments, but nothing is specifically focused around cd-setup.

**Comment by sthirugn** [comment]
sat6helper is a generic project which contains different kinds of setups.  So naming/commenting of files is very important for a developer to pick and choose what he really wants and leave the rest.

I recommend to use a file name which easily tells the user that this is tied to the content host test setup.

**Comment by JacobCallahan** [comment]
I get what you mean, but this isn't specifically tied to the content host bits. These are just general useful bash aliases and functions that I use frequently. I'll add a few comments in, and then you'll get a better understanding of what some key parts do.

**Comment by JacobCallahan** [comment]
@sthirugn Added a number of comments explaining some things.

**Comment by sthirugn** [comment]
ACK

**Pull request merged**
